// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3qoWzUWuPMYmBI-fY7psepItNaaaauU',
    appId: '1:317142953779:web:f4628c4741c30aabb85846',
    messagingSenderId: '317142953779',
    projectId: 'uh-duckpond',
    authDomain: 'uh-duckpond.firebaseapp.com',
    storageBucket: 'uh-duckpond.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkRiQRBc2DbieeiunldLD5LAtPYU3e09I',
    appId: '1:317142953779:android:d0b5b0183cf503c6b85846',
    messagingSenderId: '317142953779',
    projectId: 'uh-duckpond',
    storageBucket: 'uh-duckpond.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIUQk7rqHiqgTouI3eaagLz55krC1_yE',
    appId: '1:317142953779:ios:ff03e220eb04edd0b85846',
    messagingSenderId: '317142953779',
    projectId: 'uh-duckpond',
    storageBucket: 'uh-duckpond.appspot.com',
    iosClientId: '317142953779-vknn5turl7btsljdu0roa8vrmqavg0eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.duckPond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIIUQk7rqHiqgTouI3eaagLz55krC1_yE',
    appId: '1:317142953779:ios:ff03e220eb04edd0b85846',
    messagingSenderId: '317142953779',
    projectId: 'uh-duckpond',
    storageBucket: 'uh-duckpond.appspot.com',
    iosClientId: '317142953779-vknn5turl7btsljdu0roa8vrmqavg0eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.duckPond',
  );
}
